---
title: Olympics: Skill or 
author: Amy Townend, Sam Simmons, Dylan Williams 
output: github_document
---

## Summary
The 2022 Winter Olympics which was hosted in Beijing included the participation of 91 countries and 2871 athletes. This was the 24th Winter Olympics and it faced the lowest viewer rate in olympic history of 11.4 million viewers. The Olympics have always been a time for countries to come together among political and economic conflicts and celebrate their athletes. The time in which the Olympics were canceled was due to world wars in 1916, 1940, and 1944. When a country is chosen to to host the Olympics, it is a great honor. Countries will spend millions in order to ensure their athletes are ready to perform at the best. Sports have always been a test of natural skill but as technology has grown, so has the economic advantage. Richer countries have the disposable income to spend on the best coaches, equipment and even location. For the Winter Olympics, this is especially important to note as winter sports require even more funding to train for. In the famous movie Cool Runnings, a group of Jamaican track runners band together to become the first Jamaican bobsled team at the Olympics. This movie has a light hearted comedy feel to it but it reflects a true economic and climate advantage issue that is present with the Winter Olympics. The climate in Jamaica is hot and windy. Over the course of the year, the temperature typically varies from 73°F to 89°F and is rarely below 71°F or above 91°F. In comparison to Russia who recieves snowfall about 6 months out of the year and face temperatures below -40°F. As anyone can see, this climate in Russia gives the an automatic advantage over warmer climates such as Jamaica. For the Winter Olmpics, we see that a climate variable greatly affects tatheletes abaility to train therefore affecting medal count. 

For our project, we decided to investigate the effect of climate and economic status on medal count at the Winter 2022 Olympics. We got our data from Kaggle in which someone created a data set which was updated daily with the new medal count. In order to get climate data on the countries we chose, we were able to access another database on Kaggle which gave us the average temperatures. Finally, in order to judge how an economic status would affect a country’s ability to have good athlete participation, we downloaded a data set from the World Bank. In order to get a good feel on the number of athletes qualified vs total population, we also collected total populations from 2020 since that is the most present data we could get. In order to run our visualizations and regressions, we were able to merge these data sets in a summary data frame. This is a very preliminary study into correlations between these variables and an extensive analysis would needed to be done with much more data and variables to avoid omitted variable bias. 

Think of this as the text of your presentation. 
The length should be roughly 5 minutes when read out loud.
Although pacing varies, a 5-minute speech is roughly 750 words. 
To use the word count addin, select the text you want to count the words of (probably this is the 
Summary section of this document, go to Addins, and select the `Word count` addin).
This addin counts words using two different algorithms, but the results should be similar and as long as you're in the ballpark of 750 words, you're good! 
The addin will ignore code chunks and only count the words in prose.

You can also load your data here and present any analysis results / plots, but I strongly urge you to keep that to a minimum (maybe only the most important graphic, if you have one you can choose). 
And make sure to hide your code with  `echo = FALSE` unless the point you are trying to make is about the code itself.
Your results with proper output and graphics go in your presentation, this space is for a brief summary of your project.

```{r load-data, echo = FALSE}
# load data here, if you like
```

## Presentation

Our presentation can be found [here](presentation/presentation.html).

## Data 

Include a citation for your data here. 
See http://libraryguides.vu.edu.au/c.php?g=386501&p=4347840 for guidance on proper citation for datasets. 
If you got your data off the web, make sure to note the retrieval date.

## References

List any references here. You should, at a minimum, list your data source.

